name: Release Maven
on:
  release:
    types: [released]

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn $MAVEN_CLI_OPTS -s ./.github/settings.xml -Drevision=${{ github.ref_name }} -Dcheckstyle.skip compile

  Deploy:
    needs: [Compile]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.0.0
    with:
      version: ${{ github.ref_name }}
      jdk-version: 8
      maven-opts: '-s ./.github/settings.xml -P centralRelease'
      deploy-server-id: ossrh
      sbom: true
      sign: true
    secrets:
      GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      DEPLOY_SERVER_USER_NAME: ${{ secrets.MAVEN_CENTRAL_USER_NAME }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
