name: Build Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'

jobs:
  Version:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/next_version.yml@v1.3.0

  Compile:
    runs-on: ubuntu-latest
    needs: [Version]
    env:
      NEXT_VERSION: ${{ needs.Version.outputs.next-version }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Compile
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: mvn $MAVEN_CLI_OPTS -s ./.github/settings.xml -Drevision=$NEXT_VERSION -Dcheckstyle.skip compile

  Snapshot:
    if: github.event_name == 'push'
    needs: [Version, Compile]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.3.0
    with:
      version: ${{ needs.Version.outputs.next-version }}
      maven-opts: '-s ./.github/settings.xml'
      deploy-url-snapshot: 'https://maven.pkg.github.com/IsyFact/isyfact-bom'
    secrets:
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}