name: Build Maven
on:
  pull_request:
    branches:
      - master
      - 'release/**'
  push:
    branches:
      - master
      - 'release/**'

env:
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
  NEXT_VERSION: '2.5.0-SNAPSHOT'
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Compile
        run: mvn $MAVEN_CLI_OPTS -s ./.github/settings.xml -Drevision=$NEXT_VERSION -Dcheckstyle.skip compile

  DeployGitHubPackages:
    if: github.event_name == 'push'
    needs: [Compile]
    uses: IsyFact/isy-github-actions-templates/.github/workflows/maven_deploy_template.yml@v1.6.0
    with:
      version: '2.5.0-SNAPSHOT'
      jdk-version: 8
      maven-opts: '-s ./.github/settings.xml'
      deploy-url-snapshot: 'https://maven.pkg.github.com/IsyFact/isyfact-bom'
    secrets:
      DEPLOY_SERVER_USER_NAME: ${{ github.actor }}
      DEPLOY_SERVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}